# Generated by Django 5.1.7 on 2025-03-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('company', models.CharField(max_length=100)),
                ('trade_type', models.PositiveSmallIntegerField(choices=[(1, 'Buy'), (2, 'Sell'), (3, 'Split')])),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('price_per_share', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('split_ratio', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
